# Telegram Media Collector Bot
# Copyright (C) 2026 Vulpes Tech
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import aiohttp
import json
import os
import logging
from src.database.db import config

async def get_llm_insight(error_message: str) -> str:
    """
    Generate diagnostic insights for a given error message using the configured LLM provider.

    Args:
        error_message (str): The raw error message or traceback log.

    Returns:
        str: The diagnostic advice generated by the LLM, or None on failure.
    """
    provider = config.get('llm_provider', '').lower()
    api_key = config.get('llm_api_key', '')

    if not provider:
        return None

    try:
        with open('LLM/prompt.MD', 'r', encoding='utf-8') as f:
            prompt_template = f.read()
    except FileNotFoundError:
        prompt_template = "You are an expert system administrator. Analyze this error briefly: {error_log}"

    prompt = prompt_template.replace('{error_log}', error_message)

    try:
        async with aiohttp.ClientSession() as session:
            if provider == 'openai' or provider == 'chatgpt':
                return await _call_openai(session, api_key, prompt)
            elif provider == 'anthropic' or provider == 'claude':
                return await _call_anthropic(session, api_key, prompt)
            elif provider == 'gemini':
                return await _call_gemini(session, api_key, prompt)
            elif provider == 'groq':
                return await _call_groq(session, api_key, prompt)
            elif provider == 'local':
                return await _call_local(session, prompt)
            else:
                logging.warning(f"Unknown LLM provider: {provider}")
                return None
    except Exception as e:
        logging.error(f"LLM Insight failed: {e}")
        return None

async def _call_openai(session: aiohttp.ClientSession, api_key: str, prompt: str) -> str:
    """
    Make an API call to OpenAI's chat completions endpoint.

    Args:
        session (aiohttp.ClientSession): The HTTP client session.
        api_key (str): The OpenAI API key.
        prompt (str): The full diagnostic prompt.

    Returns:
        str: The response content or None.
    """
    model = config.get('llm_model') or "gpt-3.5-turbo"
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 8192
    }
    async with session.post("https://api.openai.com/v1/chat/completions", headers=headers, json=payload, timeout=60) as resp:
        if resp.status == 200:
            data = await resp.json()
            return data['choices'][0]['message']['content'].strip()
        return None

async def _call_anthropic(session: aiohttp.ClientSession, api_key: str, prompt: str) -> str:
    """
    Make an API call to Anthropic's messages endpoint.

    Args:
        session (aiohttp.ClientSession): The HTTP client session.
        api_key (str): The Anthropic API key.
        prompt (str): The full diagnostic prompt.

    Returns:
        str: The response content or None.
    """
    model = config.get('llm_model') or "claude-3-haiku-20240307"
    headers = {
        "x-api-key": api_key,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json"
    }
    payload = {
        "model": model,
        "max_tokens": 8192,
        "messages": [{"role": "user", "content": prompt}]
    }
    async with session.post("https://api.anthropic.com/v1/messages", headers=headers, json=payload, timeout=60) as resp:
        if resp.status == 200:
            data = await resp.json()
            return data['content'][0]['text'].strip()
        return None

async def _call_gemini(session: aiohttp.ClientSession, api_key: str, prompt: str) -> str:
    """
    Make an API call to Google's Gemini generateContent endpoint.

    Args:
        session (aiohttp.ClientSession): The HTTP client session.
        api_key (str): The Gemini API key.
        prompt (str): The full diagnostic prompt.

    Returns:
        str: The response content or None.
    """
    model = config.get('llm_model') or "gemini-2.5-flash"
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    headers = {"Content-Type": "application/json"}
    payload = {
        "contents": [{"parts": [{"text": prompt}]}],
        "generationConfig": {"maxOutputTokens": 8192}
    }
    async with session.post(url, headers=headers, json=payload, timeout=120) as resp:
        if resp.status == 200:
            data = await resp.json()
            return data['candidates'][0]['content']['parts'][0]['text'].strip()
        else:
            try:
                body = await resp.text()
                logging.error(f"Gemini API call failed with status {resp.status}: {body}")
            except Exception:
                logging.error(f"Gemini API call failed with status {resp.status}")
        return None

async def _call_groq(session: aiohttp.ClientSession, api_key: str, prompt: str) -> str:
    """
    Make an API call to Groq's completions endpoint.

    Args:
        session (aiohttp.ClientSession): The HTTP client session.
        api_key (str): The Groq API key.
        prompt (str): The full diagnostic prompt.

    Returns:
        str: The response content or None.
    """
    model = config.get('llm_model') or "llama3-8b-8192"
    headers = {"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"}
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "max_tokens": 8192
    }
    async with session.post("https://api.groq.com/openai/v1/chat/completions", headers=headers, json=payload, timeout=60) as resp:
        if resp.status == 200:
            data = await resp.json()
            return data['choices'][0]['message']['content'].strip()
        return None

async def _call_local(session: aiohttp.ClientSession, prompt: str) -> str:
    """
    Make an API call to a locally hosted LLM endpoint.

    Args:
        session (aiohttp.ClientSession): The HTTP client session.
        prompt (str): The full diagnostic prompt.

    Returns:
        str: The response content or None.
    """
    model = config.get('llm_model') or "llama3"
    local_url = config.get('llm_local_url', 'http://localhost:11434/api/generate')
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }
    async with session.post(local_url, json=payload, timeout=60) as resp:
        if resp.status == 200:
            data = await resp.json()
            return data.get('response', '').strip()
        return None
